inputs:
  secret-key:
    description: 'Secret decryption key'
    type: string
    required: true
  derivation:
    description: 'Store path to push to cache'
    type: string
    required: true
  cache-tag:
    description: 'Tag to use for the cache'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup ⚙️
      uses: nzbr/actions/nix-cache/setup@main
      with:
        secret-key: ${{ inputs.secret-key }}

    - name: Sign derivations ✒️
      shell: bash
      run: nix store sign --key-file "${{ github.action_path }}/../cache-priv-key.pem" --recursive "${{ inputs.derivation }}"

    - name: Create GC Root ♻️
      env:
        GCROOT_SUFFIX: -${{ inputs.cache-tag }}
      shell: pwsh
      run: |
        & "${{ github.action_path }}/../s3-create-gcroot.ps1" "$(nix path-info "${{ inputs.derivation }}" | head -n1)"

    - name: Copy to cache 🚚
      shell: bash
      run: nix copy --to "s3://nzbr-nix-cache?region=eu-central-1&endpoint=s3.eu-central-1.wasabisys.com&profile=nix-cache" "${{ inputs.derivation }}"
