inputs:
  expression:
    description: 'Nix expression to build'
    type: string
    required: true
  cache:
    description: 'Whether to cache the result'
    type: string
    required: false
    default: false
  cache-tag:
    description: 'Tag to use for the cache'
    type: string
    required: false
  secret-key:
    description: 'Secret decryption key'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Nix ❄️
      uses: nzbr/actions/install-nix@main

    - name: Build ${{ inputs.expression }} 🛠️
      shell: bash
      run: |
        nix build -L ${{ inputs.expression }} |& sed -uE 's/^(trace: +)?warning:(\s+|$)/::warning::/;s/^(trace: +)?error:(\s+|$)/::error::/;s/^trace:(\s+|$)/::notice::trace: /'

    - name: Cache result 🚚
      if: ${{ inputs.cache }}
      uses: nzbr/actions/nix-cache/push@main
      with:
        secret-key: ${{ inputs.secret-key }}
        derivation: ${{ inputs.expression }}
        cache-tag: ${{ inputs.cache-tag }}
